# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y php-cli php-xml
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
    sudo mv composer.phar /usr/local/bin/composer
  displayName: 'Instalar PHP y Composer'

- script: composer install
  displayName: 'Instalar Dependencias'

- script: ./vendor/bin/phpunit --testdox
  displayName: 'Ejecutar Pruebas Unitarias'
